apiVersion: apps/v1
kind: Deployment
metadata:
  name: bane
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bane
  template:
    metadata:
      labels:
        app: bane
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP